/*
 * SPDX-FileCopyrightText: 2022-2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_FONTS_FILES           85
#define MMAP_FONTS_CHECKSUM        0x2624

enum MMAP_FONTS_LISTS {
    MMAP_FONTS_ARROW_PNG = 0,        /*!< arrow.png */
    MMAP_FONTS_CLEARSKY_DAY_PNG = 1,        /*!< clearsky_day.png */
    MMAP_FONTS_CLEARSKY_NIGHT_PNG = 2,        /*!< clearsky_night.png */
    MMAP_FONTS_CLEARSKY_POLARTWILIGHT_PNG = 3,        /*!< clearsky_polartwilight.png */
    MMAP_FONTS_CLOUDY_PNG = 4,        /*!< cloudy.png */
    MMAP_FONTS_FAIR_DAY_PNG = 5,        /*!< fair_day.png */
    MMAP_FONTS_FAIR_NIGHT_PNG = 6,        /*!< fair_night.png */
    MMAP_FONTS_FAIR_POLARTWILIGHT_PNG = 7,        /*!< fair_polartwilight.png */
    MMAP_FONTS_FOG_PNG = 8,        /*!< fog.png */
    MMAP_FONTS_HEAVYRAIN_PNG = 9,        /*!< heavyrain.png */
    MMAP_FONTS_HEAVYRAINANDTHUNDER_PNG = 10,        /*!< heavyrainandthunder.png */
    MMAP_FONTS_HEAVYRAINSHOWERS_DAY_PNG = 11,        /*!< heavyrainshowers_day.png */
    MMAP_FONTS_HEAVYRAINSHOWERS_NIGHT_PNG = 12,        /*!< heavyrainshowers_night.png */
    MMAP_FONTS_HEAVYRAINSHOWERS_POLARTWILIGHT_PNG = 13,        /*!< heavyrainshowers_polartwilight.png */
    MMAP_FONTS_HEAVYRAINSHOWERSANDTHUNDER_DAY_PNG = 14,        /*!< heavyrainshowersandthunder_day.png */
    MMAP_FONTS_HEAVYRAINSHOWERSANDTHUNDER_NIGHT_PNG = 15,        /*!< heavyrainshowersandthunder_night.png */
    MMAP_FONTS_HEAVYRAINSHOWERSANDTHUNDER_POLARTWILIGHT_PNG = 16,        /*!< heavyrainshowersandthunder_polartwilight.png */
    MMAP_FONTS_HEAVYSLEET_PNG = 17,        /*!< heavysleet.png */
    MMAP_FONTS_HEAVYSLEETANDTHUNDER_PNG = 18,        /*!< heavysleetandthunder.png */
    MMAP_FONTS_HEAVYSLEETSHOWERS_DAY_PNG = 19,        /*!< heavysleetshowers_day.png */
    MMAP_FONTS_HEAVYSLEETSHOWERS_NIGHT_PNG = 20,        /*!< heavysleetshowers_night.png */
    MMAP_FONTS_HEAVYSLEETSHOWERS_POLARTWILIGHT_PNG = 21,        /*!< heavysleetshowers_polartwilight.png */
    MMAP_FONTS_HEAVYSLEETSHOWERSANDTHUNDER_DAY_PNG = 22,        /*!< heavysleetshowersandthunder_day.png */
    MMAP_FONTS_HEAVYSLEETSHOWERSANDTHUNDER_NIGHT_PNG = 23,        /*!< heavysleetshowersandthunder_night.png */
    MMAP_FONTS_HEAVYSLEETSHOWERSANDTHUNDER_POLARTWILIGHT_PNG = 24,        /*!< heavysleetshowersandthunder_polartwilight.png */
    MMAP_FONTS_HEAVYSNOW_PNG = 25,        /*!< heavysnow.png */
    MMAP_FONTS_HEAVYSNOWANDTHUNDER_PNG = 26,        /*!< heavysnowandthunder.png */
    MMAP_FONTS_HEAVYSNOWSHOWERS_DAY_PNG = 27,        /*!< heavysnowshowers_day.png */
    MMAP_FONTS_HEAVYSNOWSHOWERS_NIGHT_PNG = 28,        /*!< heavysnowshowers_night.png */
    MMAP_FONTS_HEAVYSNOWSHOWERS_POLARTWILIGHT_PNG = 29,        /*!< heavysnowshowers_polartwilight.png */
    MMAP_FONTS_HEAVYSNOWSHOWERSANDTHUNDER_DAY_PNG = 30,        /*!< heavysnowshowersandthunder_day.png */
    MMAP_FONTS_HEAVYSNOWSHOWERSANDTHUNDER_NIGHT_PNG = 31,        /*!< heavysnowshowersandthunder_night.png */
    MMAP_FONTS_HEAVYSNOWSHOWERSANDTHUNDER_POLARTWILIGHT_PNG = 32,        /*!< heavysnowshowersandthunder_polartwilight.png */
    MMAP_FONTS_LIGHTRAIN_PNG = 33,        /*!< lightrain.png */
    MMAP_FONTS_LIGHTRAINANDTHUNDER_PNG = 34,        /*!< lightrainandthunder.png */
    MMAP_FONTS_LIGHTRAINSHOWERS_DAY_PNG = 35,        /*!< lightrainshowers_day.png */
    MMAP_FONTS_LIGHTRAINSHOWERS_NIGHT_PNG = 36,        /*!< lightrainshowers_night.png */
    MMAP_FONTS_LIGHTRAINSHOWERS_POLARTWILIGHT_PNG = 37,        /*!< lightrainshowers_polartwilight.png */
    MMAP_FONTS_LIGHTRAINSHOWERSANDTHUNDER_DAY_PNG = 38,        /*!< lightrainshowersandthunder_day.png */
    MMAP_FONTS_LIGHTRAINSHOWERSANDTHUNDER_NIGHT_PNG = 39,        /*!< lightrainshowersandthunder_night.png */
    MMAP_FONTS_LIGHTRAINSHOWERSANDTHUNDER_POLARTWILIGHT_PNG = 40,        /*!< lightrainshowersandthunder_polartwilight.png */
    MMAP_FONTS_LIGHTSLEET_PNG = 41,        /*!< lightsleet.png */
    MMAP_FONTS_LIGHTSLEETANDTHUNDER_PNG = 42,        /*!< lightsleetandthunder.png */
    MMAP_FONTS_LIGHTSLEETSHOWERS_DAY_PNG = 43,        /*!< lightsleetshowers_day.png */
    MMAP_FONTS_LIGHTSLEETSHOWERS_NIGHT_PNG = 44,        /*!< lightsleetshowers_night.png */
    MMAP_FONTS_LIGHTSLEETSHOWERS_POLARTWILIGHT_PNG = 45,        /*!< lightsleetshowers_polartwilight.png */
    MMAP_FONTS_LIGHTSNOW_PNG = 46,        /*!< lightsnow.png */
    MMAP_FONTS_LIGHTSNOWANDTHUNDER_PNG = 47,        /*!< lightsnowandthunder.png */
    MMAP_FONTS_LIGHTSNOWSHOWERS_DAY_PNG = 48,        /*!< lightsnowshowers_day.png */
    MMAP_FONTS_LIGHTSNOWSHOWERS_NIGHT_PNG = 49,        /*!< lightsnowshowers_night.png */
    MMAP_FONTS_LIGHTSNOWSHOWERS_POLARTWILIGHT_PNG = 50,        /*!< lightsnowshowers_polartwilight.png */
    MMAP_FONTS_LIGHTSSLEETSHOWERSANDTHUNDER_DAY_PNG = 51,        /*!< lightssleetshowersandthunder_day.png */
    MMAP_FONTS_LIGHTSSLEETSHOWERSANDTHUNDER_NIGHT_PNG = 52,        /*!< lightssleetshowersandthunder_night.png */
    MMAP_FONTS_LIGHTSSLEETSHOWERSANDTHUNDER_POLARTWILIGHT_PNG = 53,        /*!< lightssleetshowersandthunder_polartwilight.png */
    MMAP_FONTS_LIGHTSSNOWSHOWERSANDTHUNDER_DAY_PNG = 54,        /*!< lightssnowshowersandthunder_day.png */
    MMAP_FONTS_LIGHTSSNOWSHOWERSANDTHUNDER_NIGHT_PNG = 55,        /*!< lightssnowshowersandthunder_night.png */
    MMAP_FONTS_LIGHTSSNOWSHOWERSANDTHUNDER_POLARTWILIGHT_PNG = 56,        /*!< lightssnowshowersandthunder_polartwilight.png */
    MMAP_FONTS_PARTLYCLOUDY_DAY_PNG = 57,        /*!< partlycloudy_day.png */
    MMAP_FONTS_PARTLYCLOUDY_NIGHT_PNG = 58,        /*!< partlycloudy_night.png */
    MMAP_FONTS_PARTLYCLOUDY_POLARTWILIGHT_PNG = 59,        /*!< partlycloudy_polartwilight.png */
    MMAP_FONTS_RAIN_PNG = 60,        /*!< rain.png */
    MMAP_FONTS_RAINANDTHUNDER_PNG = 61,        /*!< rainandthunder.png */
    MMAP_FONTS_RAINSHOWERS_DAY_PNG = 62,        /*!< rainshowers_day.png */
    MMAP_FONTS_RAINSHOWERS_NIGHT_PNG = 63,        /*!< rainshowers_night.png */
    MMAP_FONTS_RAINSHOWERS_POLARTWILIGHT_PNG = 64,        /*!< rainshowers_polartwilight.png */
    MMAP_FONTS_RAINSHOWERSANDTHUNDER_DAY_PNG = 65,        /*!< rainshowersandthunder_day.png */
    MMAP_FONTS_RAINSHOWERSANDTHUNDER_NIGHT_PNG = 66,        /*!< rainshowersandthunder_night.png */
    MMAP_FONTS_RAINSHOWERSANDTHUNDER_POLARTWILIGHT_PNG = 67,        /*!< rainshowersandthunder_polartwilight.png */
    MMAP_FONTS_SLEET_PNG = 68,        /*!< sleet.png */
    MMAP_FONTS_SLEETANDTHUNDER_PNG = 69,        /*!< sleetandthunder.png */
    MMAP_FONTS_SLEETSHOWERS_DAY_PNG = 70,        /*!< sleetshowers_day.png */
    MMAP_FONTS_SLEETSHOWERS_NIGHT_PNG = 71,        /*!< sleetshowers_night.png */
    MMAP_FONTS_SLEETSHOWERS_POLARTWILIGHT_PNG = 72,        /*!< sleetshowers_polartwilight.png */
    MMAP_FONTS_SLEETSHOWERSANDTHUNDER_DAY_PNG = 73,        /*!< sleetshowersandthunder_day.png */
    MMAP_FONTS_SLEETSHOWERSANDTHUNDER_NIGHT_PNG = 74,        /*!< sleetshowersandthunder_night.png */
    MMAP_FONTS_SLEETSHOWERSANDTHUNDER_POLARTWILIGHT_PNG = 75,        /*!< sleetshowersandthunder_polartwilight.png */
    MMAP_FONTS_SNOW_PNG = 76,        /*!< snow.png */
    MMAP_FONTS_SNOWANDTHUNDER_PNG = 77,        /*!< snowandthunder.png */
    MMAP_FONTS_SNOWSHOWERS_DAY_PNG = 78,        /*!< snowshowers_day.png */
    MMAP_FONTS_SNOWSHOWERS_NIGHT_PNG = 79,        /*!< snowshowers_night.png */
    MMAP_FONTS_SNOWSHOWERS_POLARTWILIGHT_PNG = 80,        /*!< snowshowers_polartwilight.png */
    MMAP_FONTS_SNOWSHOWERSANDTHUNDER_DAY_PNG = 81,        /*!< snowshowersandthunder_day.png */
    MMAP_FONTS_SNOWSHOWERSANDTHUNDER_NIGHT_PNG = 82,        /*!< snowshowersandthunder_night.png */
    MMAP_FONTS_SNOWSHOWERSANDTHUNDER_POLARTWILIGHT_PNG = 83,        /*!< snowshowersandthunder_polartwilight.png */
    MMAP_FONTS_MONTSERRATMEDIUM_TTF = 84,        /*!< MontserratMedium.ttf */
};
