#pragma once
#define CONFIG_EXAMPLE_WIFI_SSID "myssid"
#define CONFIG_EXAMPLE_WIFI_PASSWORD "mypassword"
#define CONFIG_EXAMPLE_YR_LOCATION_NAME "Oslo"
#define CONFIG_EXAMPLE_YR_LATITUDE "59.91"
#define CONFIG_EXAMPLE_YR_LONGITUDE "10.75"
#define CONFIG_EXAMPLE_YR_USER_AGENT "MultiDisplay/test"
#define CONFIG_MULTIDISPLAY_OTA_DEFAULT_URL "http://192.168.0.119:8070/manifest.json"
#define CONFIG_MULTIDISPLAY_BOARD "esp32s3-lcd-4.3"
