#pragma once
#define CONFIG_MULTIDISPLAY_WIFI_SSID "myssid"
#define CONFIG_MULTIDISPLAY_WIFI_PASSWORD "mypassword"
#define CONFIG_MULTIDISPLAY_LOCATION_NAME "Oslo"
#define CONFIG_MULTIDISPLAY_LATITUDE "59.91"
#define CONFIG_MULTIDISPLAY_LONGITUDE "10.75"
#define CONFIG_MULTIDISPLAY_USER_AGENT "MultiDisplay/test"
#define CONFIG_MULTIDISPLAY_OTA_DEFAULT_URL "http://192.168.0.119:8070/manifest.json"
#define CONFIG_MULTIDISPLAY_BOARD "esp32s3-lcd-4.3"
